server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planthelper?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 517946
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      location: D:/Win/pics
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.learn.springbootmybatis.modal
